### ISSUE TITLE
there isnt no code pls fix

### ISSUE THREAD

**Issue by EnterNewName** [SpectrixOfficial/discord-bot-info-fetcher-3000#1]
PLEASE FIX I AM ! WEEK OLD OF HTML AND MY FRIENDS SAY I CANNOT MAKE A WEBSITE APP :sob:

**Comment by SpectrixOfficial** [comment]
#  IT IS NOW COMPLETE MY CHILD I CAN'T DO `git push origin master` IN 1 SECOND IM SORRY

**Comment by EnterNewName** [comment]
lmao

**Comment by EnterNewName** [comment]
thanks dAD

**Comment by SpectrixOfficial** [comment]
Hmmm, very odd indeed. This might be because of C++ itself. This changes the laws of mathematics as we know it.... Did you try turning it on and off?
